spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8181
  servlet:
    encoding:
      force: true
    session:
      cookie:
        secure: false
