spring:
  profiles:
    active: dev
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      force: true

server:
  port: 8181
  servlet:
    session:
      cookie:
        secure: false
