spring:
  config:
     activate:
        on-profile: dev
  datasource:
    platform: h2
    url: jdbc:h2:mem:jcart;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 

app:
  jwt:
    Secret: JWTSuperSecretKey
    ExpirationInSecound: 604800
    TokenName: token
